#!/usr/bin/env python3
"""gen_web.py — 读取 web/ui.html，生成 src/web_content.h

用法: python3 gen_web.py
在 CMake 构建前自动调用，也可手动运行。
"""
import os, sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
HTML_PATH = os.path.join(SCRIPT_DIR, "web", "ui.html")
HEADER_PATH = os.path.join(SCRIPT_DIR, "src", "web_content.h")

def escape_c_string(raw: str) -> str:
    """将原始 HTML 转为安全的 C 字符串字面量内容"""
    # 先处理反斜杠，再处理双引号
    raw = raw.replace("\\", "\\\\")
    raw = raw.replace('"', '\\"')
    # 保留换行为 \n（如果有的话）
    raw = raw.replace("\r\n", "\\n").replace("\n", "\\n")
    return raw

def main():
    if not os.path.exists(HTML_PATH):
        print(f"ERROR: {HTML_PATH} not found", file=sys.stderr)
        sys.exit(1)

    with open(HTML_PATH, "r", encoding="utf-8") as f:
        html = f.read()

    escaped = escape_c_string(html)
    header = (
        "// Auto-generated by gen_web.py — DO NOT EDIT\n"
        "#pragma once\n"
        "inline const char* WEB_HTML = \"" + escaped + "\";\n"
    )

    os.makedirs(os.path.dirname(HEADER_PATH), exist_ok=True)

    # Skip write if unchanged (avoid unnecessary rebuilds)
    if os.path.exists(HEADER_PATH):
        with open(HEADER_PATH, "r", encoding="utf-8") as f:
            if f.read() == header:
                print(f"web_content.h up to date ({len(html)} bytes HTML)")
                return

    with open(HEADER_PATH, "w", encoding="utf-8") as f:
        f.write(header)

    print(f"Generated web_content.h ({len(html)} bytes HTML → {len(header)} bytes header)")

if __name__ == "__main__":
    main()
